import React, { useState, useRef, useEffect } from 'react';
import { IoMdClose } from 'react-icons/io';


const GoogleAuthVerification = ({ 
  isOpen, 
  onClose, 
  onVerify
}) => {
  const [code, setCode] = useState(['', '', '', '', '', '']);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const inputRefs = useRef([]);

  const handleChange = (index, value) => {
    // Only allow numbers
    if (!/^\d*$/.test(value)) return;

    const newCode = [...code];
    newCode[index] = value;
    setCode(newCode);
    setError('');

    // Auto-focus next input
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (index, e) => {
    // Handle backspace
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handlePaste = (e) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData('text').slice(0, 6);
    
    if (!/^\d+$/.test(pastedData)) return;

    const newCode = [...code];
    pastedData.split('').forEach((char, index) => {
      if (index < 6) {
        newCode[index] = char;
      }
    });
    setCode(newCode);

    // Focus last filled input or last input
    const lastIndex = Math.min(pastedData.length, 5);
    inputRefs.current[lastIndex]?.focus();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    const codeString = code.join('');
    if (codeString.length !== 6) {
      setError('Please enter all 6 digits');
      return;
    }

    setIsLoading(true);
    setError('');

    try {
      await onVerify(codeString);
    } catch (err) {
      setError(err.message || 'Invalid code. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/70 backdrop-blur-xl p-4 google-auth-overlay">
  <div className="relative w-full max-w-md bg-white/10 backdrop-blur-2xl border border-white/20 rounded-2xl shadow-2xl p-8 google-auth-modal overflow-hidden">

    {/* Glow Background */}
    <div className="absolute inset-0 -z-10 bg-gradient-to-br from-[#ac51fc]/40 via-purple-500/20 to-blue-600/40 blur-3xl opacity-60"></div>

    {/* Close Button */}
    <button
      className="absolute top-4 right-4 text-gray-300 hover:text-white transition google-auth-close"
      onClick={onClose}
      disabled={isLoading}
    >
      <IoMdClose size={28} />
    </button>

    <div className="relative z-10 google-auth-content">

      {/* Icon */}
      <div className="h-16 w-16 rounded-full bg-gradient-to-br from-[#ac51fc] to-purple-600 border border-white/20 shadow-lg mx-auto flex items-center justify-center text-3xl text-white google-auth-icon">
        🔐
      </div>

      {/* Title */}
      <h2 className="text-3xl font-bold text-center mt-5 text-white google-auth-title">
        Google Authenticator
      </h2>

      {/* Description */}
      <p className="text-center text-gray-300 mt-2 text-sm google-auth-description">
        Enter the 6-digit verification code generated by your Google Authenticator app
      </p>

      {/* Form */}
      <form onSubmit={handleSubmit} className="google-auth-form mt-6 space-y-6">

        {/* Inputs */}
        <div className="flex justify-center gap-3" onPaste={handlePaste}>
          {code.map((digit, index) => (
            <input
              key={index}
              ref={(el) => (inputRefs.current[index] = el)}
              type="text"
              maxLength={1}
              value={digit}
              onChange={(e) => handleChange(index, e.target.value)}
              onKeyDown={(e) => handleKeyDown(index, e)}
              autoFocus={index === 0}
              disabled={isLoading}
              className="
                w-12 h-14 rounded-xl text-center text-xl font-bold
                bg-white/10 border border-white/20 text-white backdrop-blur
                focus:border-purple-500 outline-none transition
                shadow-lg google-auth-input
              "
            />
          ))}
        </div>

        {/* Error */}
        {error && (
          <div className="text-center text-red-400 text-sm google-auth-error">
            {error}
          </div>
        )}

        {/* Button */}
        <button
          type="submit"
          disabled={isLoading || code.join("").length !== 6}
          className="
            w-full py-3 rounded-xl
            bg-gradient-to-r from-[#ac51fc] to-purple-600
            text-white font-semibold shadow-lg
            hover:opacity-90 transition disabled:opacity-50 google-auth-submit
          "
        >
          {isLoading ? "Verifying..." : "Verify & Login"}
        </button>

        <p className="text-center text-gray-400 text-sm google-auth-note">
          📱 Open your Authenticator app to view the current 6-digit code
        </p>

      </form>
    </div>
  </div>
</div>

  );
};

export default GoogleAuthVerification;
